# Generated by Django 4.0 on 2021-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
